### ISSUE TITLE
OC doesn't work in Atari

### ISSUE THREAD

**Issue by IDayday** [mklissa/MOC#3]
I'm honored to learn some of options-based work in your lab. I have reproduced the basic OC framework in pytorch. It has a good performance in fourrooms, but are not been able to learn useful knowledge in the Atari environment, so it doesn't work well.

I have noticed that some work is focused on the mujoco environment and does not use images as input, whether the OC framework's ability to learn from images is not perfect enough.

I'd like to know, have you had any experience training successfully in Atari ?

**Comment by mklissa** [comment]
Hi @IDayday,
thank you for your nice words. I'm glad that you were able to reproduce the framework in pytorch. I haven't tried MOC on Atari, but I have used it on MiniWorld (https://github.com/maximecb/gym-miniworld) which is a vision based navigation domain similar to DeepMind Lab. Let me know if you need help setting it up.
In some of the MiniWorld tasks I've seen some good improvements over the non-HRL baseline. I have to mention that the improvements seem to appear only in the case of transfer learning. Therefore, I dont expect variants of OC to show improvements on single games of Atari, or any domain for that matter, as the overhead of learning options is too big for a single simple task. 
In general there seems to be a trend towards continual learning in RL and I would expect options to work best in that setting, where you can re-use previous knowledge to better adapt to new but similar situations.
