### ISSUE TITLE
option visualization

### ISSUE THREAD

**Issue by xiaowenkaihun** [mklissa/MOC#4]
Hello, I have recently experimented with this algorithm in many scenarios and found that there is a problem of uneven distribution of options.Then I went back to the ant scene to output the options.
`            option,active_options_t = pi.get_option(ob) # line 175 in pposgd_simple.py`
I print options here.My number of options is set to 2, there are two options, 0 and 1, but in the later stage of training, the printed option has been stable at 1.I'm wondering if it's a problem with the print location I've chosen, or if there's something else.

**Comment by mklissa** [comment]
Hello, very sorry for the late reply, too many deadlines in between. Are you training the agent a in single task setting or a transfer setting? In the single task setting, this happens a lot as the agent masters the task very well and each option has seen enough of the environment to be able to solve it by itself. I have also noticed that in some runs only one option is executed later in training, my guess is that the agent takes the easy/lazy choice of always picking the same option as it doesn't see much of a difference in performance between the two options. The option-critic algorithm in general doesn't provide too much of an inductive bias or constraint, and so these kind of behaviours can happen later in training. The most straightforward way to deal with this is to add reward shaping, either through the deliberation cost or something more involved liked eigenoptions. Let me know if this helped.
